language: python
python:
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
# command to install dependencies
install:
  - "sudo apt-get build-dep python-pygame"
  - "sudo apt-get install portaudio19-dev"
  - "sudo apt-get install python-dev"
  - "pip3 install -r requirements.txt"
# command to run tests
#script: pytest
