language: python
python:
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
# command to install dependencies
before_install:
  - sudo apt-get install python-dev python3-pip python-xlib libx11-dev
  - sudo apt-get install portaudio19-dev
install:
  - pip3 install -r requirements.txt
  - pip3 install coverage coveralls
# command to run tests
script: "coverage run --source=recovoc setup.py test"

after_success:
    coveralls
